name: Download and Process MP3

on:
  workflow_dispatch:
    inputs:
      url:
        description: "YouTube视频URL"
        required: true
        type: string

jobs:
  download-and-process:
    runs-on: downloader

    env:
      PYTHONPATH: /home/junfan/test/venv/lib/python3.10

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set Branch ID
      id: set_branch_id
      run: echo "::set-output name=branch_id::$(echo ${GITHUB_SHA::8})"

    - name: Download MP3 from YouTube
      run: yt-dlp -x --audio-format mp3 -o "output.mp3" "${{ github.event.inputs.url }}"

    - name: Commit MP3 to repository
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git checkout -b process-${{ steps.set_branch_id.outputs.branch_id }}
        git add output.mp3
        git commit -m 'Add downloaded MP3 file'
        git push origin process-${{ steps.set_branch_id.outputs.branch_id }}

  process-mp3:
    runs-on: runner

    env:
      PYTHONPATH: /home/junfan/test/venv/lib/python3.10

    needs: download-and-process

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: process-${{ needs.download-and-process.outputs.branch_id }}

    - name: Process MP3 with Whisper JAX
      run: |
        from whisper_jax import FlaxWhisperPipline
        pipeline = FlaxWhisperPipline("openai/whisper-large-v2")
        text = pipeline("output.mp3")
        echo $text
