name: Transcribe MP3 on Push

on:
  push:
    branches:
      - 'process-*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  transcribe-on-push:
    if: github.event_name == 'push'
    runs-on: runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          ref: ${{ github.ref }}

      - name: Process MP3 with Whisper JAX
        run: |
          source /home/junfan/test/venv/bin/activate
          export HIP_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
          python3 << EOF
          from transformers import pipeline
          asr_pipeline = pipeline("automatic-speech-recognition", model="openai/whisper-base", device=0)
          result = asr_pipeline("output.mp3", return_timestamps=True)

          def format_timestamp(seconds):
              hours = int(seconds // 3600)
              minutes = int((seconds % 3600) // 60)
              seconds = seconds % 60
              milliseconds = int((seconds - int(seconds)) * 1000)
              return f"{hours:02}:{minutes:02}:{int(seconds):02},{milliseconds:03}"

          with open('transcript.srt', 'w', encoding='utf-8') as f:
              for i, segment in enumerate(result['chunks'], start=1):
                  start = segment['timestamp'][0]
                  end = segment['timestamp'][1]
                  text = segment['text'].strip()
                  f.write(f"{i}\n{format_timestamp(start)} --> {format_timestamp(end)}\n{text}\n\n")

          with open('transcript.txt', 'w', encoding='utf-8') as f:
              for segment in result['chunks']:
                  start = segment['timestamp'][0]
                  end = segment['timestamp'][1]
                  text = segment['text'].strip()
                  f.write(f"[{format_timestamp(start)} -> {format_timestamp(end)}] {text}\n")

          print("Transcription completed and saved.")
          EOF

      - name: Commit Transcript
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git remote set-url origin https://${{ github.actor }}:${{ env.PAT_TOKEN }}@github.com/${{ github.repository }}
          git add transcript.srt transcript.txt
          git commit -m 'Add transcription files'
          git push origin ${{ github.ref }}

  find-branches:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    outputs:
      branches: ${{ steps.set-branches.outputs.branches }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: List branches
        id: set-branches
        run: |
          git fetch --all
          BRANCHES=$(git ls-remote --heads origin "process-*" | awk '{print $2}' | sed 's|refs/heads/||')
          echo "Found branches:"
          echo "$BRANCHES"

          BRANCHES_TO_PROCESS=()
          for BRANCH in $BRANCHES; do
            echo "Checking branch $BRANCH"
            if ! git ls-tree -r --name-only origin/$BRANCH | grep -qE 'transcript\.txt|transcript\.srt'; then
              echo "Branch $BRANCH does not have transcript files."
              BRANCHES_TO_PROCESS+=("$BRANCH")
            else
              echo "Branch $BRANCH already has transcript files."
            fi
          done

          echo "Branches to process: ${BRANCHES_TO_PROCESS[@]}"
          echo "::set-output name=branches::$(printf '%s\n' "${BRANCHES_TO_PROCESS[@]}" | jq -R -s -c 'split("\n") | map(select(length > 0))')"

  transcribe-on-dispatch:
    if: github.event_name == 'workflow_dispatch' && needs.find-branches.outputs.branches != '[]'
    needs: [find-branches]
    runs-on: runner
    strategy:
      matrix:
        branch: ${{ fromJson(needs.find-branches.outputs.branches) }}
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          ref: ${{ matrix.branch }}

      - name: Process MP3 with Whisper JAX
        run: |
          source /home/junfan/test/venv/bin/activate
          export HIP_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
          python3 << EOF
          from transformers import pipeline
          asr_pipeline = pipeline("automatic-speech-recognition", model="openai/whisper-base", device=0)
          result = asr_pipeline("output.mp3", return_timestamps=True)

          def format_timestamp(seconds):
              hours = int(seconds // 3600)
              minutes = int((seconds % 3600) // 60)
              seconds = seconds % 60
              milliseconds = int((seconds - int(seconds)) * 1000)
              return f"{hours:02}:{minutes:02}:{int(seconds):02},{milliseconds:03}"

          with open('transcript.srt', 'w', encoding='utf-8') as f:
              for i, segment in enumerate(result['chunks'], start=1):
                  start = segment['timestamp'][0]
                  end = segment['timestamp'][1]
                  text = segment['text'].strip()
                  f.write(f"{i}\n{format_timestamp(start)} --> {format_timestamp(end)}\n{text}\n\n")

          with open('transcript.txt', 'w', encoding='utf-8') as f:
              for segment in result['chunks']:
                  start = segment['timestamp'][0]
                  end = segment['timestamp'][1]
                  text = segment['text'].strip()
                  f.write(f"[{format_timestamp(start)} -> {format_timestamp(end)}] {text}\n")

          print("Transcription completed and saved.")
          EOF

      - name: Commit Transcript
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git remote set-url origin https://${{ github.actor }}:${{ env.PAT_TOKEN }}@github.com/${{ github.repository }}
          git add transcript.srt transcript.txt
          git commit -m 'Add transcription files'
          git push origin ${{ matrix.branch }}
