name: Transcribe MP3 on Push

on:
  push:
    branches:
      - 'process-*'
  workflow_dispatch:
    inputs:
      batch_number:
        description: 'Batch number to process (starting from 1)'
        required: false
        default: '1'

permissions:
  contents: write

jobs:
  transcribe-on-push:
    if: github.event_name == 'push'
    runs-on: runner
    timeout-minutes: 180
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          ref: ${{ github.ref }}

      - name: Process MP3 with Whisper JAX
        id: transcribe
        run: |
          source /home/junfan/test/venv/bin/activate
          export HIP_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
          python3 .github/workflows/convert2txt.py

      - name: Commit Transcript
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git remote set-url origin https://${{ github.actor }}:${{ env.GH_TOKEN }}@github.com/${{ github.repository }}
          
          if [[ -f transcript.srt && -f transcript.txt ]]; then
            git add transcript.srt transcript.txt
            if ! git diff --staged --quiet; then
              git commit -m 'Add transcription files'
              git push origin ${{ github.ref }}
            else
              echo "No changes to commit"
            fi
          else
            echo "Error: Transcription files not found"
            exit 1
          fi

  find-branches:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    outputs:
      total_batches: ${{ steps.calculate-batches.outputs.total_batches }}
      batch_branches: ${{ steps.calculate-batches.outputs.batch_branches }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: List and categorize branches
        id: list-branches
        run: |
          mkdir -p branch_info
          
          # Get all process-* branches
          BRANCHES=$(git ls-remote --heads origin "process-*" | awk '{print $2}' | sed 's|refs/heads/||')
          echo "$BRANCHES" > branch_info/all_branches.txt
          
          # Initialize branch category files
          > branch_info/branches_to_process.txt
          > branch_info/branches_with_transcripts.txt
          > branch_info/branches_without_mp3.txt
          
          for BRANCH in $BRANCHES; do
            git fetch origin $BRANCH:refs/remotes/origin/$BRANCH --force
            
            if ! git ls-tree -r --name-only origin/$BRANCH HEAD | grep -qE 'transcript\.txt|transcript\.srt'; then
              if git ls-tree -r --name-only origin/$BRANCH | grep -q 'output.mp3'; then
                echo "$BRANCH" >> branch_info/branches_to_process.txt
              else
                echo "$BRANCH" >> branch_info/branches_without_mp3.txt
              fi
            else
              echo "$BRANCH" >> branch_info/branches_with_transcripts.txt
            fi
          done

      - name: Calculate Batches
        id: calculate-batches
        run: |
          BATCH_SIZE=256
          BATCH_NUMBER="${{ github.event.inputs.batch_number }}"
          BATCH_NUMBER=${BATCH_NUMBER:-1}
          
          if [ ! -f "branch_info/branches_to_process.txt" ] || [ ! -s "branch_info/branches_to_process.txt" ]; then
            echo "No branches to process"
            echo "total_batches=0" >> $GITHUB_OUTPUT
            echo "batch_branches=[]" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          TOTAL_BRANCHES=$(wc -l < "branch_info/branches_to_process.txt")
          TOTAL_BATCHES=$(( (TOTAL_BRANCHES + BATCH_SIZE - 1) / BATCH_SIZE ))
          
          if [ "$BATCH_NUMBER" -gt "$TOTAL_BATCHES" ]; then
            echo "Error: Batch number $BATCH_NUMBER exceeds total batches $TOTAL_BATCHES"
            exit 1
          fi
          
          START_INDEX=$(( (BATCH_NUMBER - 1) * BATCH_SIZE + 1 ))
          END_INDEX=$(( BATCH_NUMBER * BATCH_SIZE ))
          if [ $END_INDEX -gt $TOTAL_BRANCHES ]; then
            END_INDEX=$TOTAL_BRANCHES
          fi
          
          # Create JSON array properly
          echo "Creating batch array from index $START_INDEX to $END_INDEX"
          BATCH_BRANCHES=$(sed -n "${START_INDEX},${END_INDEX}p" "branch_info/branches_to_process.txt" | \
                          sed 's/^/"/; s/$/"/' | \
                          paste -sd, - | \
                          sed 's/^/[/; s/$/]/')
          
          # Write outputs
          echo "total_batches=$TOTAL_BATCHES" >> $GITHUB_OUTPUT
          echo "batch_branches=$BATCH_BRANCHES" >> $GITHUB_OUTPUT
          echo "$BATCH_BRANCHES" > "branch_info/batch_branches.json"
          
          # Debug output
          echo "Total branches: $TOTAL_BRANCHES"
          echo "Total batches: $TOTAL_BATCHES"
          echo "Current batch: $BATCH_NUMBER"
          echo "Batch branches: $BATCH_BRANCHES"

      - name: Upload branch information
        uses: actions/upload-artifact@v3
        with:
          name: branch-info
          path: branch_info/
          retention-days: 90

  transcribe-on-dispatch:
    if: github.event_name == 'workflow_dispatch'
    needs: [find-branches]
    runs-on: runner
    timeout-minutes: 1440  # 24 hours
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download branch information
        uses: actions/download-artifact@v3
        with:
          name: branch-info
          path: branch_info

      - name: Process branches
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          source /home/junfan/test/venv/bin/activate
          export HIP_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
          
          if [ ! -f branch_info/branches_to_process.txt ] || [ ! -s branch_info/branches_to_process.txt ]; then
            echo "No branches need processing"
            exit 0
          fi
          
          # Configure git
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git remote set-url origin https://${{ github.actor }}:${{ env.GH_TOKEN }}@github.com/${{ github.repository }}
          
          # Process each branch
          while IFS= read -r branch; do
            echo "Processing branch: $branch"
            
            if ! git checkout "$branch"; then
              echo "Failed to checkout branch: $branch"
              continue
            fi
            
            git pull origin "$branch"
            
            if [ ! -f output.mp3 ]; then
              echo "No output.mp3 found in branch: $branch"
              continue
            fi
            
            if python3 .github/workflows/convert2txt.py; then
              if [[ -f transcript.srt && -f transcript.txt ]]; then
                git add transcript.srt transcript.txt
                if ! git diff --staged --quiet; then
                  git commit -m "Add transcription files for $branch"
                  if git push origin "$branch"; then
                    echo "Successfully processed branch: $branch"
                  else
                    echo "Failed to push changes for branch: $branch"
                  fi
                else
                  echo "No changes to commit for branch: $branch"
                fi
              else
                echo "Transcription failed for branch: $branch"
              fi
            else
              echo "Processing failed for branch: $branch"
            fi
          done < branch_info/branches_to_process.txt
